name: Test & Deploy
on: [push]
jobs:
    test-utils:
        name: test utils
        runs-on: ubuntu-latest
        steps:
            -   name: checkout and clone Repo
                uses: actions/checkout@v3
            -   name: install dependencies
                run: npm install
            -   name: run utils tests
                run: npm run test-utils

    test-app:
        name: test app
        runs-on: ubuntu-latest
        steps:
            -   name: checkout and clone Repo
                uses: actions/checkout@v3
            -   name: install dependencies
                run: npm install
            -   name: setup postgres
                uses: harmon758/postgresql-action@v1
                with:
                    postgresql db: test_db
                    postgresql user: qwerty
                    postgresql password: ytrewq
            -   name: run app tests
                run: PGDATABASE=test_db PGUSER=qwerty PGPASSWORD=ytrewq npm test
    test-app-live-db:
        needs: test-app
        name: test-app
        runs-on: ubuntu-latest
        steps:
            -   name: checkout and clone Repo
                uses: actions/checkout@v3
            -   name: install dependencies
                run: npm install
            -   name: run live db app tests
                run: NODE_ENV=production DATABASE_URL=${{secrets.DATABASE_URL}} npm test